baseURL = 'https://blogitesti.netlify.app/'
languageCode = 'en-us'
title = 'Testisivusto'
theme = "ananke"

[[menu.main]]
  name = "Tietoa Seurasta"
  url = "/tietoa-seurasta/"
  weight = 2

[[menu.main]]
  name = "Pelaajat"
  url = "/pelaajat/"
  weight = 3

[params]
  mainSections = ["posts"]