backend:
  name: git-gateway
  branch: main # Tai master, jos se on reposi päähaara

media_folder: "static/images/uploads" # Mihin kuvat tallennetaan
public_folder: "/images/uploads" # Miten kuviin viitataan sivuilla

collections:
  # uutiset / tiedotteet jne...
  - name: "post"
    label: "Uutiset"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Otsikko", name: "title", widget: "string"}
      - {label: "Julkaisupäivä", name: "date", widget: "datetime"}
      - {label: "Leipäteksti", name: "body", widget: "markdown"}

  # sivut
  - name: "pages"
    label: "Sivut"
    files:
      - file: "content/tietoa-seurasta.md"
        label: "Tietoa seurasta -sivu"
        name: "tietoa_seurasta"
        fields:
          - {label: "Otsikko", name: "title", widget: "string"}
          - {label: "Leipäteksti", name: "body", widget: "markdown"}

  # pelaajat
  - name: "pelaajat"
    label: "Pelaajat"
    folder: "content/pelaajat"
    create: true
    slug: "{{pelipaikka}}-{{sukunimi}}-{{etunimi}}"
    fields:
      - {label: "Etunimi", name: "etunimi", widget: "string"}
      - {label: "Sukunimi", name: "sukunimi", widget: "string"}
      - {label: "Pelinumero", name: "pelinumero", widget: "number", required: false}
      - {label: "Pelipaikka", name: "pelipaikka", widget: "string", required: false}
      - {label: "Syntymäaika", name: "syntymaaika", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD.MM.YYYY", time_format: false, required: false}
      - {label: "Pituus", name: "pituus", widget: "string", required: false}
      - {label: "Pelaajan kuva", name: "kuva", widget: "image", required: false}
      - {label: "Kausi", name: "kausi", widget: "string", hint: "Esim. 2024-2025 tai Entinen pelaaja"}
      - {label: "Esittelyteksti", name: "body", widget: "markdown"}