backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  # KOKOELMA 1: Uutiset
  - name: "post"
    label: "Uutiset"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Otsikko", name: "title", widget: "string"}
      - {label: "Julkaisupäivä", name: "date", widget: "datetime"}
      - {label: "Leipäteksti", name: "body", widget: "rich_text"}

  # KOKOELMA 2: Sivut
  - name: "pages"
    label: "Sivut"
    files:
      - file: "content/tietoa-seurasta.md"
        label: "Tietoa seurasta -sivu"
        name: "tietoa_seurasta"
        fields:
          - {label: "Otsikko", name: "title", widget: "string"}
          - {label: "Leipäteksti", name: "body", widget: "rich_text"}
      # Voit lisätä muita yksittäisiä sivuja tänne, esim. Yhteistyökumppanit

  # KOKOELMA 3: Pelaajat
  - name: "pelaajat"
    label: "Pelaajat"
    folder: "content/pelaajat"
    create: true
    slug: "{{pelipaikka}}-{{sukunimi}}-{{etunimi}}"
    fields:
      - {label: "Etunimi", name: "etunimi", widget: "string"}
      - {label: "Sukunimi", name: "sukunimi", widget: "string"}
      - {label: "Pelinumero", name: "pelinumero", widget: "number", required: false}
      - {label: "Pelipaikka", name: "pelipaikka", widget: "string", required: false}
      - {label: "Syntymäaika", name: "syntymaaika", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD.MM.YYYY", time_format: false, required: false}
      - {label: "Pituus", name: "pituus", widget: "string", required: false}
      - {label: "Pelaajan kuva", name: "kuva", widget: "image", required: false}
      - {label: "Kausi", name: "kausi", widget: "select", options: ["2024-2025", "2023-2024", "Entinen pelaaja"]}
      - {label: "Esittelyteksti", name: "body", widget: "rich_text"}

  # KOKOELMA 4: Ottelut
  - name: "ottelut"
    label: "Ottelut"
    folder: "content/ottelut"
    create: true
    slug: "{{fields.paivamaara}}-{{fields.kotijoukkue}}-vs-{{fields.vierasjoukkue}}"
    fields:
      - {label: "Ottelun päivämäärä", name: "paivamaara", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD.MM.YYYY", time_format: false}
      - {label: "Kellonaika", name: "kellonaika", widget: "string", hint: "Esim. 18:30"}
      - label: "Kotijoukkue"
        name: "kotijoukkue"
        widget: "select"
        options:
          - "Kobrat"
          - "Bisons Loimaa"
          - "Helsinki Seagulls"
          - "KTP-Basket"
          - "Kataja Basket"
          - "Korihait"
          - "BC Nokia"
          - "Salon Vilpas"
          - "Tampereen Pyrintö"
          - "Karhu Basket"
          # Lisää loput Korisliigan joukkueet tähän
      - label: "Vierasjoukkue"
        name: "vierasjoukkue"
        widget: "select"
        options:
          - "Kobrat"
          - "Bisons Loimaa"
          - "Helsinki Seagulls"
          - "KTP-Basket"
          - "Kataja Basket"
          - "Korihait"
          - "BC Nokia"
          - "Salon Vilpas"
          - "Tampereen Pyrintö"
          - "Karhu Basket"
          # Lisää loput Korisliigan joukkueet tähän
      - {label: "Onko kotipeli?", name: "onko_kotipeli", widget: "boolean", default: true}
      - {label: "Pelipaikka", name: "pelipaikka", widget: "string"}
      - {label: "Lopputulos", name: "tulos", widget: "string", required: false, hint: "Täytetään ottelun jälkeen, esim. 98-92"}

  # KOKOELMA 5: 